# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: objective-c
xcode_sdk: iphonesimulator10.1

# cache: cocoapods
podfile: Examples/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Examples


script:
  - set -o pipefail && xcodebuild test -workspace Examples/TinyPlayerDemo+Benchmark.xcworkspace -scheme TinyPlayerDemo -destination “platform=iOS Simulator,name=iPhone 6S” ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
